name: Build

on: [push, pull_request]

jobs:
  tests:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-20.04, macos-11]
        python-version: [3.5, 3.6, 3.7, 3.8, 3.9, "3.10", "3.11-dev", "pypy-3.7"]

    steps:

    - uses: actions/checkout@v3

    - name: Use Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - run: pip install tox virtualenv

    - run: "make jq.c"

    - run: tox -e py

  build_sdist:
    name: Build source distribution
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        name: Use Python 3.7
        with:
          python-version: '3.7'

      - run: make jq.c

      - run: pip install build twine

      - name: Build sdist
        run: python -m build --sdist

      - name: Check metadata
        run: python -m twine check dist/*

      - uses: actions/upload-artifact@v3
        with:
          path: dist/*.tar.gz

  build_wheels_matrix:
    name: Generate matrix for building wheels
    runs-on: ubuntu-latest

    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}

    steps:

      - uses: actions/checkout@v3

      - name: Install cibuildwheel
        run: pipx install cibuildwheel==2.11.2

      - id: set-matrix
        env:
          CIBW_ARCHS_LINUX: "auto aarch64"
          CIBW_ARCHS_MACOS: "auto"
        run: |
          MATRIX=$(
            {
              cibuildwheel --print-build-identifiers --platform linux \
                | jq --raw-input --compact-output --null-input '{"cibw-only": inputs, "os": "ubuntu-20.04"}' \
              && cibuildwheel --print-build-identifiers --platform macos \
                | jq --raw-input --compact-output --null-input '{"cibw-only": inputs, "os": "macos-11"}'
            } | jq --slurp --compact-output '{"include": .}'
          )
          echo matrix="$MATRIX" >> $GITHUB_OUTPUT

  build_wheels:
    name: Build ${{ matrix.cibw-only }} wheel

    needs: build_wheels_matrix

    strategy:
      matrix: ${{ fromJson(needs.build_wheels_matrix.outputs.matrix) }}

    runs-on: ${{ matrix.os }}

    steps:

    - uses: actions/checkout@v3

    - name: Set up QEMU
      if: runner.os == 'Linux'
      uses: docker/setup-qemu-action@v1
      with:
        platforms: all

    - name: Build wheels
      if: ${{ (github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags/')) || matrix.cibw-only == 'cp310-manylinux_x86_64' }}
      uses: pypa/cibuildwheel@v2.11.2
      with:
        only: ${{ matrix.cibw-only }}

    - uses: actions/upload-artifact@v3
      if: ${{ (github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags/')) || matrix.cibw-only == 'cp310-manylinux_x86_64' }}
      with:
        path: ./wheelhouse/*.whl
